// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {diary} from '../models';

export function DeleteEntry(arg1:string):Promise<void>;

export function GetCurrentUser():Promise<string>;

export function GetEntry(arg1:string):Promise<diary.DiaryEntry|boolean>;

export function ListDates():Promise<Array<string>>;

export function Login(arg1:string,arg2:string):Promise<string>;

export function Logout():Promise<void>;

export function Register(arg1:string,arg2:string):Promise<void>;

export function SaveEntry(arg1:string,arg2:string,arg3:string):Promise<void>;
